FROM node:18-alpine

# Set working directory
WORKDIR /app

# Install dependencies
COPY package.json package-lock.json* ./
RUN npm install

# No need to copy source files as they will be mounted as a volume

# Expose React development server port
EXPOSE 3000

# Start React development server
CMD ["npm", "start"]